### ISSUE TITLE
Executing Permissions for all for binaries

### ISSUE THREAD

**Issue by sw360cab** [SavageCore/node-ffprobe-installer#12]
Differently from its sibling node-ffmpeg-installer, the executables for ffprobe comes without "execution permissions for all" (a+x) [at least in the linux_x64 version].
Although this is not a problem for the correctness of the module itself, it represents a limitation in environments such as AWS Lambda which requires "execution permissions for all" to execute binaries.

**Comment by deevus** [comment]
A solution that worked for me was to copy the executable to temp and set `+x` on it there.

**Comment by sw360cab** [comment]
Yes, this is a valid workaroud.
Although IMHO commiting the permissions modified on the executable file would completely solve the issue.

**Comment by SavageCore** [comment]
Good point. Happy to accept a PR if anyone gets around to this before me!

**Comment by tomgallagher** [comment]
I'm struggling to get this working on AWS Lambda as well

Has anyone had any success?

**Comment by sw360cab** [comment]
I am using it on AWS Lambda. If you are taking the version with my patch metged, it will work.

**Comment by tomgallagher** [comment]
Thanks for getting back. Is that the latest published version on NPM?

**Comment by sw360cab** [comment]
This is what I was wondering. I think it does....
To verify that (or fix that), try locally that the **ffbrobe** binary in
node_modules folders is getting the 'x' permission correctly (a+x)

I suggest using it in a Layer in AWS Lambda.


Il giorno mer 15 mag 2019 alle ore 12:32 Turbo <notifications@github.com>
ha scritto:

**Comment by tomgallagher** [comment]
OK. I'll take a look. Thanks.

Never used Layers - I'm developing with AWS Cloud 9 so the advantage of seeing everything in the Lambda console is not relevant to me. There seem to be other advantages too. I need to read more.

**Comment by sw360cab** [comment]
OffTopic:
Layers allow you to create a "layer" with dependencies and to deploy
quickly only the part of your code/app which is changing avoiding to
include every time all the dependencies (which will reside in the layer
itself)

Il giorno mer 15 mag 2019 alle ore 12:48 Turbo <notifications@github.com>
ha scritto:

**Comment by tomgallagher** [comment]
I'm copying the executable to a temporary file path.

Here's a stupid beginners question: how do I allow execution permissions in Lambda for my temporary file?

This code:

```
const ffprobeExecutable = tempy.file({ extension: 'tmp' });
fs.createReadStream(ffprobe.path).pipe(fs.createWriteStream(ffprobeExecutable, {mode: 0o755}));
```

returns spawn ETXTBSY error when I am trying to run this command in fluent ffmpeg:

```
ffmpeg.ffprobe(videoInputFile, function(err, metadata) {
     if (err) { reject(err); }
     console.dir(metadata);
});
```
