### ISSUE TITLE
On some systems, resolving Google Drive fails

### ISSUE THREAD

**Issue by csillag** [SavageCore/node-ffprobe-installer#135]
We have encountered an issue with GoogleDrive on _some_ of our developer systems.

We are using ffprobe @ 1.1.0, which depends on 
"@ffprobe-installer/linux-x64": "4.1.0",
which installs this version:

```
ffprobe version N-48944-g9b069eb14e-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2019 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
```

And when I run this binary:

```
./node_modules/@ffprobe-installer/linux-x64/ffprobe  "https://drive.google.com/uc?export=download&id=1xSCWuqKG-YRhqE0LnuazY5bYTSqo3nC4"
ffprobe version N-48944-g9b069eb14e-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 52.102 / 58. 52.102
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 54.101 /  7. 54.101
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
[tcp @ 0x7011dc0] Failed to resolve hostname doc-0k-30-docs.googleusercontent.com: System error
https://drive.google.com/uc?export=download&id=1xSCWuqKG-YRhqE0LnuazY5bYTSqo3nC4: Input/output error                   
```

The key is in the penultimate line:
**[tcp @ 0x7011dc0] Failed to resolve hostname doc-0k-30-docs.googleusercontent.com: System error**

Note that simply running the ffprobe that I have on my own system, the same command runs without any errors.
So I guess it must be the ffprobe version in question, or one of the statically linked libraries.

The trick is that at another developer box, the same issue doesn't manifest... so it might be tricky to test this.
(I am willing to help.)

I guess we should move away from the ffprobe build from 2017?

Thanks.

**Comment by akakumani** [comment]
+1 I believe it's related to this issue:

https://superuser.com/questions/1141609/android-tcp-error-failed-to-resolve-host-name-from-static-library

Essentially, it seems dns resolution is affected. I was facing the same issue with another static library before moving to this one. My issue is the same as yours in that it fails in the docker environment, but passes locally on my mac.

**Comment by SavageCore** [comment]
I shall update all the builds within the next day or 2

Let's hope that helps :)

**Comment by SavageCore** [comment]
Guys, update to [v1.2.0](https://github.com/SavageCore/node-ffprobe-installer/releases/tag/v1.2.0) with all new binaries and let's hope!

**Comment by SavageCore** [comment]
No updates, closing.

**Comment by cgilly2fast** [comment]
> Guys, update to [v1.2.0](https://github.com/SavageCore/node-ffprobe-installer/releases/tag/v1.2.0) with all new binaries and let's hope!

Lets hope? Wild. Its still an issue.
