### ISSUE TITLE
Support for darwin-arm64

### ISSUE THREAD

**Issue by MatchaDog** [SavageCore/node-ffprobe-installer#141]
I got an error `Unsupported platform/architecture: darwin-arm64` on my Macbook pro M1;
Support for M1 maybe awesome for node-ffprobe-installer

**Comment by SavageCore** [comment]
Does anyone know of a good source for FFprobe static builds? Happy to support a proper PR with the source listed in readme

**Comment by binarykitchen** [comment]
Yes please this is bugging me enormously. Can you please work on it pretty please?

**Comment by binarykitchen** [comment]
Pleeeeeaaaaaassseeeeee ????????

**Comment by eisenyang** [comment]
> Does anyone know of a good source for FFprobe static builds? Happy to support a proper PR with the source listed in readme

I  compiled my static ffmpeg & ffprob on my m1 mbp.
ref: https://www.osxexperts.net

**Comment by naranjamecanica** [comment]
M1 Macbook Pro = no go experiencing the same issue

**Comment by hus-o** [comment]
> > Does anyone know of a good source for FFprobe static builds? Happy to support a proper PR with the source listed in readme
> 
> I compiled my static ffmpeg & ffprob on my m1 mbp. ref: https://www.osxexperts.net

I can see ffmpeg there but no reference to ffprobe, also how would you change a projects package.json to use the static versions of each?

**Comment by eisenyang** [comment]
> > > Does anyone know of a good source for FFprobe static builds? Happy to support a proper PR with the source listed in readme
> > 
> > 
> > I compiled my static ffmpeg & ffprob on my m1 mbp. ref: https://www.osxexperts.net
> 
> I can see ffmpeg there but no reference to ffprobe, also how would you change a projects package.json to use the static versions of each?

ffmpeg / ffmprob / ffplay now have full native support now.
https://ffmpeg.org/download.html
https://evermeet.cx/ffmpeg/

**Comment by SavageCore** [comment]
@eisenyang What do you mean by full native support? As far as I can see evermeet is [not providing ARM builds](https://evermeet.cx/ffmpeg/apple-silicon-arm) still.

["I do not plan to provide native ffmpeg binaries for Apple Silicon ARM."](https://evermeet.cx/ffmpeg/#remarks)

**Comment by eisenyang** [comment]
> @eisenyang What do you mean by full native support? As far as I can see evermeet is [not providing ARM builds](https://evermeet.cx/ffmpeg/apple-silicon-arm) still.
> 
> ["I do not plan to provide native ffmpeg binaries for Apple Silicon ARM."](https://evermeet.cx/ffmpeg/#remarks)

https://www.toolfarm.com/news/apple-silicon-compatibility/
```
FFMpeg
Full native support with Homebrew
```
But Sorry, just `with Homebrew` got full native support.

We still need to compile ourselves.

**Comment by eisenyang** [comment]
> > > Does anyone know of a good source for FFprobe static builds? Happy to support a proper PR with the source listed in readme
> > 
> > 
> > I compiled my static ffmpeg & ffprob on my m1 mbp. ref: https://www.osxexperts.net
> 
> I can see ffmpeg there but no reference to ffprobe, also how would you change a projects package.json to use the static versions of each?

ffprobe  for apple silicon just uploaded:
https://drive.google.com/drive/folders/1UX7HT2ezc1Ta6LxcKtksXKrQCQO247oA

**Comment by binarykitchen** [comment]
Just a little compliment here, you guys are awesome! Keep going please.

PS: I need this to be fixed for a video service which helps Deaf people to exchange emails in Sign Language. Thanks.

**Comment by binarykitchen** [comment]
Hooray, thanks @Kikobeats
