### ISSUE TITLE
Could not find ffprobe executable with nest.js

### ISSUE THREAD

**Issue by fenfil** [SavageCore/node-ffprobe-installer#186]
Error: Could not find ffprobe executable, tried "/Users/fenfil/Projects/back/dist/apps/api/node_modules/ffprobe-darwin-arm64/ffprobe" and "/Users/fenfil/Projects/back/dist/apps/api/src/node_modules/ffprobe-darwin-arm64/ffprobe"

Actual executable is in "/Users/fenfil/Projects/back/node_modules/ffprobe-darwin-arm64/ffprobe""

**Comment by Lugana707** [comment]
Having a similar issue:

```bash
Error: Could not find ffprobe executable, tried "/src/dist/node_modules/@ffprobe-installer/linux-x64/ffprobe" and "/src/dist/src/node_modules/@ffprobe-installer/linux-x64/ffprobe"
```
```JSON
{
    "@nestjs/common": "^7.6.15",
    "@ffprobe-installer/ffprobe": "^1.2.0",
}
```

**Comment by mcottret** [comment]
There are actually 2 NPM packages & repositories for this project:

- [`@ffprobe-installer/ffprobe`](https://www.npmjs.com/package/@ffprobe-installer/ffprobe) which references [this repo](https://github.com/SavageCore/node-ffprobe-installer)
- [`node-ffprobe-installer`](https://www.npmjs.com/package/node-ffprobe-installer) which references [a newer fork](https://github.com/Honeyside/node-ffprobe-installer)

A [`node-ffprobe-installer` update](https://github.com/Honeyside/node-ffprobe-installer/commit/04bf02ea36ee5769cbc6730ad541a7e3b2235783) seems to have broken the path resolution in some environments, including NestJS' local one. Issues are not enabled on their repo, but maybe @Beekiper can help :)
While waiting for a fix, sticking to [`@ffprobe-installer/ffprobe`](https://www.npmjs.com/package/@ffprobe-installer/ffprobe) should prevent this issue.

Be careful as the wrong package might still be registered as a dependency of one of your dependencies (for example [`get-video-duration`](https://github.com/caffco/get-video-duration) updated it from [3.0.2](https://github.com/caffco/get-video-duration/blob/v3.0.2/package.json#L11) to [3.1.0](https://github.com/caffco/get-video-duration/blob/v3.1.0/package.json#L13).

**Comment by SavageCore** [comment]
@mcottret Thanks for explaining that.

Closed as not applicable? Feel free to reopen if still an issue.

**Comment by Beekiper** [comment]
The other package exists because I added arm64 support for M1 Apple Silicon. Sorry but uploading a second one was the only way to deliver a product of ours on time!

I have never used Nest therefore I have no idea how to fix this.
