### ISSUE TITLE
NPM Version 1.4.0 was supposed to update darwin-arm64 FFprobe, it didn't

### ISSUE THREAD

**Issue by MohamedBakoush** [SavageCore/node-ffprobe-installer#206]
https://www.npmjs.com/package/@ffprobe-installer/ffprobe - updated from version 1.3.0 to 1.4.0

https://www.npmjs.com/package/@ffprobe-installer/darwin-arm64 - didn't get a version update, currently at 5.0.0 making npm download the old version of ffprobe `1dd6aab8b1880c44cc98db96f950634ad701848a` supposed to be `384491447b76b483cfd32c99e9f6327f201e19a3`
 
platforms/darwin-arm64 needs to be uploaded for NPM to recognize new ffprobe binary `384491447b76b483cfd32c99e9f6327f201e19a3` 

As stated [README.md](https://github.com/kribblo/node-ffmpeg-installer/blob/master/README.md#upload-new-versions)

> ## Upload new versions
> 
> In every updated `platforms/*` directory:
>  
>     npm run upload

**Comment by SavageCore** [comment]
Thanks, fixed in v1.4.1
