### ISSUE TITLE
permissions issues with darwin-arm64 version

### ISSUE THREAD

**Issue by marcelblum** [SavageCore/node-ffprobe-installer#207]
First many thanks for providing what appears to be the only static prebuild of ffprobe for darwin-arm64 on the web.

I noticed the ffprobe binary as npm-installed comes with unusual permissions. It's `-rwxr--r--` which leads to some weirdness at least on a new Mac with default settings. On my M1 Mac just out of the box, ffprobe can only run from the terminal successfully using `sudo`. In Finder, macOS won't even give it the 'unix executable' icon and it can't be double clicked to open in Terminal. And it fails to run from within any Node process with an access denied. I was able to fix it locally by doing a quick `chmod 777 ffprobe` and then all was fine.

Happy to submit the modded binary as a pr if that helps, though honestly I don't know enough about how npm install handles unix permissions on downloaded files to know whether the permissions metadata even carries over when npm fetches the file (or for that matter when I push a git commit with it). Or whether this is an issue better handled by the install script instead.

Related: #12

**Comment by SavageCore** [comment]
Interesting, `chmod u+x ffprobe` is ran as `postinstall` and should give your user executable access. What happens if you run `chmod +x ffprobe`? I like to avoid 777.

**Comment by marcelblum** [comment]
Hi - Revisiting this 1 year later, on the same M1 MBP, now well used, updated to Ventura, and reconfigured for use as a developer's machine, a fresh `npm install @ffprobe-installer/ffprobe` works as expected and I'm no longer seeing the problem described above. The ffprobe arm64 binary that comes down the tubes is fully executable as is and has the right icon. I'm going to guess this has something to do with whatever default settings this machine came with out of the box which have long since been tweaked by me many times over by now. The file still ends up with `-rwxr--r--` permissions.

**Comment by SavageCore** [comment]
> Hi - Revisiting this 1 year later, on the same M1 MBP, now well used, updated to Ventura, and reconfigured for use as a developer's machine, a fresh `npm install @ffprobe-installer/ffprobe` works as expected and I'm no longer seeing the problem described above. The ffprobe arm64 binary that comes down the tubes is fully executable as is and has the right icon. I'm going to guess this has something to do with whatever default settings this machine came with out of the box which have long since been tweaked by me many times over by now. The file still ends up with `-rwxr--r--` permissions.

Great news! Closing
