### ISSUE TITLE
possible to install latest version?

### ISSUE THREAD

**Issue by JuanIrache** [SavageCore/node-ffprobe-installer#215]
Hi. Nice job with this.

Is there a way to install the latest Git master version? Like with

> brew install homebrew-ffmpeg/ffmpeg/ffmpeg --HEAD

https://github.com/homebrew-ffmpeg/homebrew-ffmpeg#installing-latest-git-version-head

Thank you

**Comment by SavageCore** [comment]
I'm afraid not, updating the binaries is a manual process.
