### ISSUE TITLE
Release 1.4.2 introduced breaking changes for older NodeJS 14.x

### ISSUE THREAD

**Issue by lfernando-silva** [SavageCore/node-ffprobe-installer#246]
Hey, just to let you aware that this last release breaks for some older NodeJS versions before 14.21.2. In my case, due [this](https://github.com/SavageCore/node-ffprobe-installer/commit/34cf8b30256dcad557dcf46099a3c1040fde5ed5) commit.

I understand that I should keep my NodeJS versions updated to LTS, what is not always simple and can trick us in some CI runs and production. 

But anyway, it is just to help people who maybe is having the same issue since the last release.

**Comment by SavageCore** [comment]
Thanks for highlighting that!

I've deprecated `v1.4.2` and released it as `v2.0.0` to signify a breaking change.
