### ISSUE TITLE
 throws Error: EACCES: permission denied

### ISSUE THREAD

**Issue by tomgallagher** [SavageCore/node-ffprobe-installer#33]
Hi

I know this has been raised already but I'm trying to use the package from NPM on AWS Lambda in exactly the same way as the node-ffmpeg-installer. When running fluent ffmpeg with ffprobe I'm getting this error. I have tried to copy the executable to a temp file and change the permissions as in (https://github.com/SavageCore/node-ffprobe-installer/issues/12) but I cannot get it to work. 

Any help much appreciated.

**Comment by SavageCore** [comment]
Have you seen this issue https://github.com/kribblo/node-ffmpeg-installer/issues/21#issuecomment-449763544? Should hopefully solve the problem here and I will add to readme.
